# =========================================================================
# SNIPPET MODULER: PESUPELUH (TANPA BUNGKUS SERVER)
# =========================================================================
location /pesupeluh {
    alias /var/www/pesupeluh/public;
    try_files $uri $uri/ @pesupeluh-backend;

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
    }
}

location @pesupeluh-backend {
    rewrite ^/pesupeluh/(.*)$ /pesupeluh/index.php?/$1 last;
}
